import test from 'node:test';
import assert from 'node:assert/strict';
import {emptyState,migrateLegacy,legacyPayload,applyOperations,values,active,weight,monthData,generateKey,vaultCredentials,seal,unseal,validateState,classLabel,importBase} from './core.mjs';
import {VaultStore} from './store.mjs';
import * as core from './core.mjs';
const original={id:'123',client:'Maria Exemplo',cat:'cap',value:200000,nota:8,stage:'Negociação',subtype:'STVM',date:'2026-09-20',next:'Telefonar',notes:'Saldo informado no C6.',alloc:['RF'],snoozeUntil:'2026-09-15',archivedAt:'2026-09-01T12:00:00Z',customLegacyField:'preservar'};
test('full backup imports preserve client tiers, assets, custom classes and goals',()=>{const source=emptyState();source.clients.x={id:'x',name:'Client',tier:'D'};source.assets.a={id:'a',clientId:'x',institution:'C6',class:'Renda Fixa',value:200000};source.settings.goals.cap=900000;source.settings.classes.items.push('Custom');const imported=applyOperations(emptyState(),importBase(source,emptyState()));assert.equal(imported.clients.x.tier,'D');assert.equal(imported.assets.a.value,200000);assert.equal(imported.settings.goals.cap,900000);assert.ok(imported.settings.classes.items.includes('Custom'));imported.settings.goals.cap=1100000;const again=applyOperations(imported,importBase(source,imported));assert.equal(again.settings.goals.cap,1100000);});
test('migration preserves every original pipe field, client relationship and original snapshot',()=>{
  const source={pipes:[original,{...original,id:'124',cat:'rv'}],history:[{...original,id:'125',outcome:'Ganho',closedAt:'2026-09-12T12:00:00Z'}]};const before=JSON.stringify(source);
  const m=migrateLegacy(source),s=applyOperations(emptyState(),m.operations);assert.equal(m.addedClients,1);assert.equal(m.addedPipes,3);assert.equal(m.retired,1);
  const p=s.pipes['legacy-pipe-123'];for(const key of Object.keys(original).filter(k=>k!=='id'))assert.deepEqual(p[key],original[key]);assert.deepEqual(p.legacyOriginal,original);assert.equal(s.clients[p.clientId].name,original.client);assert.equal(s.pipes['legacy-pipe-124'].retired,true);assert.equal(s.pipes['legacy-pipe-125'].outcome,'Ganho');assert.equal(JSON.stringify(source),before);
});
test('repeated migration is idempotent and cannot undo a new edit or deletion',()=>{const first=migrateLegacy({pipes:[original]});let s=applyOperations(emptyState(),first.operations);s=applyOperations(s,[{type:'pipes',id:'legacy-pipe-123',patch:{value:900000,deletedAt:'2026-09-13'}}]);const second=migrateLegacy({pipes:[original]},s);s=applyOperations(s,second.operations);assert.equal(second.addedPipes,0);assert.equal(s.pipes['legacy-pipe-123'].value,900000);assert.equal(s.pipes['legacy-pipe-123'].deletedAt,'2026-09-13');assert.equal(Object.keys(s.clients).length,1);});
test('cloud backup migration retains existing targets, manual results and MEREO overrides',()=>{
  const data={'ricoPipeline.v4':JSON.stringify([original]),'ricoPipeline.goals':JSON.stringify({cap:1500000,rv:500000}), 'ricoPipeline.manualReal':JSON.stringify({'2026-8':{aloc:123,rv:45}}),'ricoPipeline.mereo':JSON.stringify({'2026-8':{ovCap:999,nps:88,cards:3}})};
  const m=migrateLegacy({data}),s=applyOperations(emptyState(),m.operations);assert.equal(s.settings.goals.cap,1500000);assert.equal(s.settings.goals.rv,500000);assert.equal(s.settings.manual['2026-8'].rv,45);assert.equal(s.settings.mereo['2026-8'].ovCap,999);assert.equal(Object.values(s.imports)[0].source.data['ricoPipeline.v4'],data['ricoPipeline.v4']);
});
test('legacy source precedence matches the old application, including backup fallback',()=>{assert.equal(legacyPayload({data:{'ricoPipeline.v4':'[]','ricoPipeline.backup':JSON.stringify([original])}}).pipes.length,1);assert.equal(legacyPayload({data:{'ricoPipeline.v4':JSON.stringify([original]),'ricoPipeline.backup':JSON.stringify([{...original,value:1}])}}).pipes[0].value,200000);assert.equal(legacyPayload({data:{'ricoPipeline.history.v1':'[]','ricoPipeline.history.backup':JSON.stringify([original])}}).history.length,0);});
test('client classification stays manual and independent of pipe priority',()=>{const s=applyOperations(emptyState(),migrateLegacy({pipes:[original]}).operations),p=s.pipes['legacy-pipe-123'];assert.equal(s.clients[p.clientId].tier,undefined);const next=applyOperations(s,[{type:'clients',id:p.clientId,patch:{tier:'D'}}]);assert.equal(next.clients[p.clientId].tier,'D');assert.equal(next.pipes[p.id].nota,8);});
test('exact normalized client names reuse one record; different names remain distinct',()=>{const s=applyOperations(emptyState(),migrateLegacy({pipes:[original,{...original,id:'b',client:'  MARIA   EXEMPLO '},{...original,id:'c',client:'Maria Outra'}]}).operations);assert.equal(Object.keys(s.clients).length,2);});
test('unknown pipe categories are archived rather than discarded or silently reclassified',()=>{const s=applyOperations(emptyState(),migrateLegacy([{...original,cat:'custom'}]).operations);assert.equal(s.pipes['legacy-pipe-123'].cat,'custom');assert.equal(s.pipes['legacy-pipe-123'].retired,true);});
test('closed copy takes precedence when legacy active and history contain the same ID',()=>{const m=migrateLegacy({pipes:[original],history:[{...original,outcome:'Perdido'}]});assert.equal(m.addedPipes,1);assert.equal(applyOperations(emptyState(),m.operations).pipes['legacy-pipe-123'].outcome,'Perdido');});
test('soft deletion hides records and restoration recovers the same values',()=>{let s=emptyState();s.pipes.x={...original,id:'x'};const before=structuredClone(s.pipes.x);s=applyOperations(s,[{type:'pipes',id:'x',patch:{deletedAt:'2026-09-13'}}]);assert.equal(values(s,'pipes').length,0);s=applyOperations(s,[{type:'pipes',id:'x',patch:{deletedAt:null}}]);assert.equal(values(s,'pipes').length,1);assert.equal(s.pipes.x.value,before.value);});
test('closed, retired, deleted and future-snoozed pipes are not active',()=>{assert.equal(active({...original,snoozeUntil:null}),true);for(const patch of [{outcome:'Ganho'},{retired:true},{deletedAt:'now'},{snoozeUntil:'2999-01-01'}])assert.equal(active({...original,...patch}),false);});
test('goal calculations preserve 1.25 weighting, month boundaries and legacy RV results',()=>{const s=emptyState();s.pipes={a:{...original,id:'a',outcome:'Ganho',closedAt:'2026-09-12T12:00:00',subtype:'Previdência'},b:{...original,id:'b',cat:'rv',value:300000,retired:true,outcome:'Ganho',closedAt:'2026-09-10T12:00:00'},c:{...original,id:'c',outcome:'Ganho',closedAt:'2026-08-10T12:00:00'}};s.settings.manual={'2026-8':{aloc:10000,rv:1000,cap:5000}};const m=monthData(s,'2026-09');assert.equal(weight(original),1.25);assert.equal(m.realized.cap,255000);assert.equal(m.realized.aloc,311000);assert.equal(m.components.find(c=>c.name==='Cesta investimento').value,561000);});
test('MEREO scores 3 at target with original crossell points and weights',()=>{const s=emptyState();s.settings.mereo={'2026-8':{ovCap:800000,ovAloc:2200000,ovSeg:12000,ovCon:100000,cards:3,ic:83,nps:41.3}};const m=monthData(s,'2026-09');assert.equal(m.components.find(c=>c.name==='Crossell').value,25);assert.ok(Math.abs(m.score-3)<1e-10);});
test('HTML-shaped client data remains text in persisted model; unsafe record IDs rejected',()=>{const s=emptyState();assert.throws(()=>applyOperations(s,[{type:'clients',id:'__proto__',patch:{x:1}}]));assert.throws(()=>validateState({version:3}));assert.equal(classLabel('Fundos Listados'),'Fundos Imobiliários');});
test('vault encryption authenticates contents, uses random nonces and a separate document key',async()=>{const access=generateKey(),{id,key}=await vaultCredentials(access);assert.ok(!id.includes(access.slice(5)));const s=emptyState();s.clients.a={name:'Private Client',tier:'A'};const a=await seal(s,key),b=await seal(s,key);assert.notEqual(a.iv,b.iv);assert.ok(!JSON.stringify(a).includes('Private Client'));assert.deepEqual(await unseal(a,key),s);const other=await vaultCredentials(generateKey());await assert.rejects(unseal(a,other.key));a.ciphertext='X'+a.ciphertext.slice(1);await assert.rejects(unseal(a,key));});
class MemoryStorage{map=new Map();getItem(k){return this.map.get(k)||null;}setItem(k,v){this.map.set(k,v);}}
class MemoryTransport{docs=new Map();counter=0;offline=false;conflictOnce=false;async read(id){if(this.offline)throw Error('network offline');return structuredClone(this.docs.get(id)||null);}async write(id,envelope,stamp){if(this.offline)throw Error('network offline');const old=this.docs.get(id);if(this.conflictOnce){this.conflictOnce=false;throw Object.assign(Error('conflict'),{status:409});}if((old?.stamp||null)!==stamp)throw Object.assign(Error('conflict'),{status:409});const doc={envelope,stamp:String(++this.counter)};this.docs.set(id,doc);return structuredClone(doc);}}
async function settled(store){while(store.busy)await new Promise(r=>setTimeout(r,3));await store.serial;}
test('two devices merge edits to separate clients and fields without overwriting a base',async()=>{const transport=new MemoryTransport(),access=generateKey(),a=new VaultStore({transport,storage:new MemoryStorage()}),b=new VaultStore({transport,storage:new MemoryStorage()});try{await a.open(access,{create:true});await b.open(access);await settled(a);await settled(b);await a.commit([{type:'clients',id:'one',patch:{id:'one',name:'One',tier:'A'}}]);await settled(a);await b.commit([{type:'clients',id:'two',patch:{id:'two',name:'Two',tier:'D'}}]);await settled(b);await a.sync();await b.sync();assert.equal(Object.keys(a.state.clients).length,2);assert.deepEqual(a.state,b.state);transport.conflictOnce=true;await a.commit([{type:'clients',id:'one',patch:{tier:'B'}}]);await settled(a);await b.commit([{type:'clients',id:'one',patch:{notes:'Keep tier from other device'}}]);await settled(b);assert.equal(b.state.clients.one.tier,'B');assert.equal(b.state.clients.one.notes,'Keep tier from other device');}finally{await a.close();await b.close();}});
test('offline edits survive an encrypted cache reload and sync later',async()=>{const transport=new MemoryTransport(),storage=new MemoryStorage(),access=generateKey();let a=new VaultStore({transport,storage});try{await a.open(access,{create:true});await settled(a);transport.offline=true;await a.commit([{type:'clients',id:'one',patch:{id:'one',name:'Saved offline'}}]);await settled(a);const cache=storage.getItem(a.cacheKey);assert.ok(!cache.includes('Saved offline'));await a.close();a=new VaultStore({transport,storage});await a.open(access);await settled(a);assert.equal(a.state.clients.one.name,'Saved offline');assert.equal(a.pending.length,1);transport.offline=false;await a.sync();assert.equal(a.pending.length,0);const {key,id}=await vaultCredentials(access);assert.equal((await unseal((await transport.read(id)).envelope,key)).clients.one.name,'Saved offline');}finally{await a.close();}});
test('local storage failure rolls back the edit instead of reporting it saved',async()=>{const transport=new MemoryTransport(),storage=new MemoryStorage(),s=new VaultStore({transport,storage});try{await s.open(generateKey(),{create:true});await settled(s);storage.setItem=()=>{throw Error('quota');};await assert.rejects(s.commit([{type:'clients',id:'bad',patch:{name:'Not saved'}}]));assert.equal(s.state.clients.bad,undefined);assert.equal(s.pending.length,0);}finally{await s.close();}});
test('deleted data is not revived by a stale unrelated edit from another device',async()=>{const transport=new MemoryTransport(),key=generateKey(),a=new VaultStore({transport,storage:new MemoryStorage()}),b=new VaultStore({transport,storage:new MemoryStorage()});try{await a.open(key,{create:true});await a.commit([{type:'pipes',id:'x',patch:{...original,id:'x'}}]);await settled(a);await b.open(key);await settled(b);await a.commit([{type:'pipes',id:'x',patch:{deletedAt:'2026-09-13'}}]);await settled(a);await b.commit([{type:'pipes',id:'x',patch:{notes:'Edited concurrently'}}]);await settled(b);assert.equal(b.state.pipes.x.deletedAt,'2026-09-13');assert.equal(values(b.state,'pipes').length,0);}finally{await a.close();await b.close();}});
test('estimated position: sliders become one asset per class and zeroed classes are removed',()=>{
  const assets=[];
  const ops=core.estimateOperations(assets,'c1','Rico',500000,{'Renda Fixa':45,'Previdência':20,'Renda Variável':15,'Multimercados':0,'Não informado':20},'2026-09-14');
  assert.equal(ops.length,4);
  const state=core.applyOperations({...core.emptyState(),clients:{c1:{id:'c1',name:'X'}}},ops);
  const est=core.estimateOf(Object.values(state.assets),'c1','rico');
  assert.equal(est.total,500000);assert.deepEqual(est.pct,{'Renda Fixa':45,'Previdência':20,'Renda Variável':15,'Não informado':20});
  const ops2=core.estimateOperations(Object.values(state.assets),'c1','Rico',400000,{'Renda Fixa':100,'Previdência':0,'Renda Variável':0,'Não informado':0},'2026-09-15');
  const state2=core.applyOperations(state,ops2);
  const live=Object.values(state2.assets).filter(a=>!a.deletedAt);
  assert.equal(live.length,1);assert.equal(live[0].class,'Renda Fixa');assert.equal(live[0].value,400000);
});
